[build]
  command = "npm run build"
  publish = "_site/"
	
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[build.environment]
[build.environment]
  RUBY_VERSION = "3.2.9"
  BUNDLER_VERSION = "2.7.2"